inertial_frame_id: world
waypoints:
  -
    point: [0, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 10, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 20, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 30, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 40, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [10, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [20, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [30, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [40, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [60, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [70, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [80, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [90, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 50, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 40, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 30, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 20, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 10, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [90, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [80, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [70, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [60, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [40, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [30, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [20, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [10, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 0, -20]
    max_forward_speed: 2.5
    heading: 0
    use_fixed_heading: False
